### ISSUE TITLE
HttpError 

### ISSUE THREAD

**Issue by imtrinity94** [izayl/spotify-box#8]
<img width="679" alt="image" src="https://user-images.githubusercontent.com/7029361/153569027-a6fb2506-101b-44db-b012-c0094a7526fb.png">

I am using https://gist.github.com/imtrinity94/fd1a7057b85170b25114706d284d32f1 as GIST_ID and Create_Gist role for token.

**Comment by izayl** [comment]
Have you ever tried following steps?
> Go to your fork's Settings > Environments > New environment and create an environment called "prod"
Choose your "prod" environment and Add Secret for each environment secret (below)

**Comment by imtrinity94** [comment]
yes it seem i did. I will follow all steps again.

**Comment by TOBEACODER7** [comment]
> Have you ever tried following steps?
> 
> > Go to your fork's Settings > Environments > New environment and create an environment called "prod"
> > Choose your "prod" environment and Add Secret for each environment secret (below)

Hey～I met the same error. And I have created prod environment and added all secrets. But I also met this problem. Is there another reason for this problem?

**Comment by izayl** [comment]
@TOBEACODER7 I test your gist_id `ad51b608e153f971d6fb4e90dc7ae607` with my gh_token, and it works, so I think maybe you missed to set the `gh_token` env.

additional, I'll update env variables check

**Comment by izayl** [comment]
@TOBEACODER7  I just update the code, and if your env config is wrong, you could see the error log from actions. If there still have issue, welcome to reopen it again

**Comment by TOBEACODER7** [comment]
> @TOBEACODER7 I just update the code, and if your env config is wrong, you could see the error log from actions. If there still have issue, welcome to reopen it again

okay! I have a try~ Thanks

**Comment by TOBEACODER7** [comment]
> @TOBEACODER7 I just update the code, and if your env config is wrong, you could see the error log from actions. If there still have issue, welcome to reopen it again

The problem is caused by my rudeness. I directly copy my gist`s URL as GIST_ID. It`s so embarrassing. Thanks for your help!
